# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76cc1b60816d27e58ea081e74dfa22b26da38f17ecdcd809892a89a8755cce2df73b3d65ed1e6e8e56643d4d72e8aae4a06f9d820c2cf0b2e7122bfe90bec08

test:
  secret_key_base: 46e2ffde484d1ff4febc538c2a134bcbdc7688605b23a1fcec3b38ada8da0646ad3be9257899e8b5265839d82125aedbfb438c22e2b0aefbf0c27e6130218bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
